version: '3.0'

services:
  grafana:
    container_name: 'grafana-clock-panel'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.2.4}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-clock-panel
      - ./provisioning:/etc/grafana/provisioning
